# Generated by Django 5.2 on 2025-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_stadium',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AlterField(
            model_name='add_stadium',
            name='service_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
