# Generated by Django 5.2.1 on 2025-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_stadium',
            name='event_types',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
